let jugadores = {
    lista: [
    { 
        id: "1",
        nombre: "Paulo Bruno Exequiel",
        apellido: "Dybala",
        edad: "28",
        nacimiento: "15/11/1993",
        nacionalidad: "Argentina", 
        club: "Juventus",
        posicion:"Mediapunta",
        trayectoria: "Instituo Central de Cordoba(2011-2012); Palermo(2012-2015); Juventus(2015-2022)",
        fisico: "Mide 1,77m y pesa 77kg",
        valorDeMercado: "40 millones de euros",
        
    },
    { 
        id: "2",
        nombre: "Lionel Andres",
        apellido: "Messi",
        edad: "34",
        nacimiento: "24/6/1987",
        nacionalidad: "Argentina", 
        club: "PSG",
        posicion: "Delantero-Extremo Derecho",
        trayectoria: "Newells(1995-2000); FC Barcelona(2004-2021); PSG(2021-actualmente)",
        fisico: "Mide 1,69m y pesa 67kg",
        valorDeMercado: "60 millones de euros",
        id: "2",

    },
    { 
        id: "3",
        nombre: "Robert",
        apellido: "Lewandoski",
        edad: "33",
        nacimiento: "21/08/1988",
        nacionalidad: "Polonia", 
        club: "Bayern Munich",
        posicion: "Delantero centro",
        trayectoria: "Mide 1,85 m y pesa 81 kg",
        fisico: "Legia de Varsovia II(2005-2006); Znicz Pruszkow(2006-2008); Lech Poznan(2008-2010); B.V Borussia(2010-2014); FC Bayern Munich(2014-actualmente)",
        valorDeMercado: "50 millones de euros",

    },
    { 
        id: "4",
        nombre: "Zlatan",
        apellido: "Ibrahimovic",
        edad: "40",
        nacimiento:"03/10/1981",
        nacionalidad: "Suecia", 
        club: "AC Milan",
        posicion:"Delantero centro",
        trayectoria: "Malmo(1999-2001); Ajax(2001-2004); Juventus(2004-2006); Internazionale(2006-2009); FC Barcelona(2009-2010); A.C Milan(2010-2012); PSG(2012-2016); Manchester United(2016-2018); L.A Galaxy(2018-2019); A.C Milan(2020-actualmente)",
        fisico: "Mide 1,95m y pesa 95kg",
        valorDeMercado: "4 millones de euros",

    },
    { 
        id: "5",
        nombre: "N'Golo",
        apellido: "Kante",
        edad: "31",
        nacimiento: "29/03/1991",
        nacionalidad: "Francia", 
        club: "Chelsea FC",
        posicion: "Mediocampista",
        trayectoria: "U.S Boulogne(2012-2013); S.M Caen(2013-2015); Leicester City (2015-2016); Chelsea FC(2016-actualmente)",
        fisico: "Mide 1,68m y pesa 68kg",
        valorDeMercado: "50 millones de euros",

    },
    { 
        id: "6",
        nombre: "Julian",
        apellido: "Alvarez",
        edad: "22",
        nacimiento: "31/01/200",
        nacionalidad: "Argetnina", 
        club: "River Plate",
        posicion: "Delantero centro",
        trayectoria: "River Plate(2018-2021); Manchester City F.C(2022-presente); prestamo de River Plate (2022-presente)",
        fisico: "Mide 1,70m y pesa 71kg",
        valorDeMercado: "23 millones de euros",

},
{ 
        id: "7",
        nombre: "Phil",
        apellido: "Foden",
        edad: "21",
        nacimiento: "28/05/2000",
        nacionalidad: "Inglaterra", 
        club: "Manchester City",
        posicion: "Mediocentro",
        trayectoria: "Manchester City(2017-actualmente)",
        fisico: "Mide 1,71m y pesa 61kg",
        valorDeMercado: "90 millones de euros",

},
{ 
        id: "8",    
        nombre: "Pablo Martin",
        apellido: "Páez Gavira (Gavi)",
        edad: "17",
        nacimiento: "05/08(2004",
        nacionalidad: "España", 
        club: "FC Barcelona",
        posicion: "Mediocentro",
        trayectoria: "FC Barcelona(2020-actualmente)",
        fisico: "Mide 1,71m y pesa 65kg",
        valorDeMercado: "60 millones de euros",

},
{ 
        id: "9",
        nombre: "Juan Fernando",
        apellido: "Quintero",
        edad: "29",
        nacimiento: " 18/01/1993",
        nacionalidad: "Colombia", 
        club: "River Plate",
        posicion: "Mediocentro ofensivo",
        trayectoria: "Envigado(2009-1011); Atlético Nacional(2012); Delfino Pescara(2012-2013); F.C Porto(2013-2018); Stade Rennes(2015-2016); Independiente Medellín(2017); River Plate(2018); River Plate(2019-20); Shenzhen FC(2021); River Plate(2022-actualmente)",
        fisico: "Mide 1,68m y pesa 65kg",
        valorDeMercado: "6 millones de euros",

},
{ 
        id: "10",
        nombre: "Nahuel",
        apellido: "Molina",
        edad: "24",
        nacimiento: "06/04/1998",
        nacionalidad: "Argentina", 
        club: "Udinese",
        posicion: "Lateral derecho",
        trayectoria: "Boca Juniors(2016-2020); → Defensa y Justicia(2018); → Rosario Central(2019); Udinese(2020-actualmente.)",
        fisico: "Mide 1,75m y pesa 70kg",
        valorDeMercado: "10 millones de euros",

},

    ]
}

module.exports = jugadores;  